jobs:
  - job: 'Windows'
    strategy:
      matrix:
        Python34:
          python.version: '3.4'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    pool:
      vmImage: 'vs2017-win2016'
    timeoutInMinutes: 360
    steps:

      - script: python setup.py test
